version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_jdbc
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql